### PR TITLE
Add Gaius_sama as Polkadot Delegate

### PR DESCRIPTION
**Pull request by Gunit2481**
Adding Gaius_sama (me) as Polkadot Delegate.

### CODE REVIEW

**Comment by Gunit2481** [comment]
Extrinsic ID: https://polkadot.subscan.io/extrinsic/16901315-2

**Comment by stepanLav** [comment]
Hello @Gunit2481 ,
Thank you for request!
Sorry for the delay, there is how it will looks like int the app:
<details>
  <summary>Screens</summary>

Screenshot 2023-09-01 at 20 34 21 3
Screenshot 2023-09-01 at 20 39 16
Screenshot 2023-09-01 at 20 39 19



</details>

**Review by stepanLav — APPROVED** [review]

**Comment by stepanLav** [comment]
I've made a little changes to improve your formating

**Comment by Gunit2481** [comment]
Hi @stepanLav.

Thanks for correcting my markdown, it looks good to me. 

You can continue!

**Pull request merged**
