### PR TITLE
Update polkadot.json

### PR DESCRIPTION
**Pull request by TheeWeb3Patriot**
Theeweb3patriot delegation update

### CODE REVIEW

**Comment by TheeWeb3Patriot** [comment]
https://polkadot.subscan.io/extrinsic/20725267-2

**Comment by stepanLav** [comment]
Hello @TheeWeb3Patriot !
Thank you for the request, could you also provide the image from the config - TheeWeb3Patriot.png ?

**Comment by TheeWeb3Patriot** [comment]
TheeWeb3Patriot
this is the image

**Review by stepanLav — APPROVED** [review]

**Comment by stepanLav** [comment]
Added:
<details>
  <summary>Spoiler!</summary>

IMG_8158
IMG_8159

</details>

**Pull request merged**
