### PR TITLE
 Add Polkadotters to delegate registry

### PR DESCRIPTION
**Pull request by pmensik**
this PR will add Polkadotters as one of the delegates for OpenGov.

### CODE REVIEW

**Comment by stepanLav** [comment]
Hello @pmensik!
Thank you for PR, we'll check it out soon. Could you provide proof of ownership of that accounts? You can do it based on that [tutorial](https://docs.novawallet.io/nova-wallet-wiki/governance/add-delegate-information), step 14

**Comment by pmensik** [comment]
Hey @stepanLav,

here is the proof for Kusama
https://kusama.subscan.io/extrinsic/18365781-2

and for Polkadot
https://polkadot.subscan.io/extrinsic/15976551-2

Thank you!

**Comment by stepanLav** [comment]
Ty, everything looks good, this is how it will looks like in the app:
<details>
  <summary>Spoiler!</summary>

Screenshot 2023-06-23 at 07 34 48
Screenshot 2023-06-23 at 07 34 52
Screenshot 2023-06-23 at 07 34 55


</details>

**Review by stepanLav — APPROVED** [review]

**Comment by pmensik** [comment]
Hey @stepanLav, looks awesome, thank you!

**Pull request merged**
