### PR TITLE
Ho Si Hanh

### PR DESCRIPTION
**Pull request by HoSiHanh**

### CODE REVIEW

**Comment by HoSiHanh** [comment]
I would like you to register a delegate.
Thank you for your support.

**Comment by stepanLav** [comment]
Hello! Thank you for the request, could you add a proof via system.remark for that address, please?

**Comment by HoSiHanh** [comment]
Dear StepanLav
Thank you very much for contacting me. 
I'm sorry. Where do I "add a proof via system.remark"? Could you please tell me?

**Comment by stepanLav** [comment]
> Dear StepanLav Thank you very much for contacting me. I'm sorry. Where do I "add a proof via system.remark"? Could you please tell me?

You can use this [tutorial](https://docs.novawallet.io/nova-wallet-wiki/opengov/delegate-registry)

**Comment by HoSiHanh** [comment]
Dear StepanLav
I've finally registered.
I will send you my system (remark) extrinsic ID.
Thank you.
https://kusama.subscan.io/extrinsic/24881821-2

**Review by stepanLav — APPROVED** [review]

**Pull request merged**
